library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libraryapp/', include('libraryapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register')
]

library/libraryapp/urls.py
from django.urls import path
from . import views

app_name = 'libraryapp' # for namespacing
urlpatterns = [
    path('add_book/', views.add_book, name='add_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('checkout_book/<int:pk>/', views.checkout_book, name='checkout_book'),
    path('return_book/<int:pk>', views.return_book, name='return_book'),
    path('', views.index, name='index'),
]

library/libraryapp/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User

# Create your models here.

class Author(models.Model):
    author_name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.author_name

class Book(models.Model):
    title = models.CharField(max_length=250, default="Title not specified")
    publish_date = models.DateTimeField()
    author = models.ForeignKey(Author, on_delete=models.SET_DEFAULT, default="Author not specified")

    def __str__(self):
        return self.title

class Availability(models.Model):
    user = models.CharField(max_length=250, default='Currently Available')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    checkout = models.BooleanField(default=False)
    timestamp = models.DateField(default=date.today())

    def __str__(self):
        return self.book

library/library/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.clean_password2()
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            return redirect('libraryapp:index')
            # return HttpResponse(f'User:{user}, Pass:{password}')
        else:
            return HttpResponse("Invalid Form")
    context = {
    'form':UserCreationForm()
    }
    return render(request, 'registration/register.html', context)

library/libraryapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Book, Author, Availability
# Create your views here.

def index(request):
    book_list = Availability.objects.all()
    context = {'books':book_list}
    return render(request, 'libraryapp/index.html', context)

# @login_required
def add_book(request):
    if request.method == "POST":
        new_author_name = request.POST['author_name']
        new_title = request.POST['title']
        new_publish_date = request.POST['publish_date']
        if not Author.objects.filter(author_name=new_author_name).exists():
            create_new_author = Author(author_name=new_author_name)
            create_new_author.save()
        author_id = Author.objects.filter(author_name=new_author_name)[0]
        new_book = Book(title=new_title, publish_date=new_publish_date, author=author_id)
        new_book.save()
        new_availability = Availability(book=new_book)
        new_availability.save()
    return HttpResponseRedirect(reverse('libraryapp:index'))

# @login_required
def delete_book(request, pk):
    target_book = get_object_or_404(Availability, pk=pk)
    target_book.delete()
    return HttpResponseRedirect(reverse('libraryapp:index'))

# @login_required
def checkout_book(request, pk):
    target_book = get_object_or_404(Availability, pk=pk)
    target_book.user = request.user.username
    if target_book.checkout:
        target_book.user = 'Currently Available'
    target_book.checkout = (not target_book.checkout)
    target_book.save()
    return HttpResponseRedirect(reverse('libraryapp:index'))

# @login_required
def return_book(request, pk):
    return HttpResponse('Book returned')

library/libraryapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %} </title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>

library/libraryapp/templates/libraryapp/index.html
{% extends "base_generic.html" %}
{% block title %}Library App{% endblock title %}

{% block content %}
<div>
  <a href="{% url 'register' %}" method="GET">
    <button type="submit">Create New User</button>
  </a>
  <p></p>
  <a href="{% url 'login' %}" method="GET">
    <button type="submit">Login</button>
  </a>
  <p></p>
  <a href="{% url 'logout' %}" method="GET">
    <button type="submit">Logout</button>
  </a>
</div>
Add a Book:
<form action="{% url 'libraryapp:add_book' %}" method="POST">
  {% csrf_token %}
  Title<input type="text" name="title"/>
  Date Published<input type="datetime" name="publish_date" placeholder="YYYY-MM-DD"/>
  Author Name<input type="text" name="author_name"/>
  <button type="submit">Add Book</button>
</form>
<ul>
  {% for book_item in books %}
  <li>
    <p {% if book_item.checkout %}class="checked_out"{% endif %}>{{ book_item.book.title }} by {{book_item.book.author.author_name}}</p>
    <!-- <p>{{ book_item.completed }}</p> -->
    <p>{{ book_item.user }}</p>
    <form action="{% url 'libraryapp:checkout_book' book_item.pk %}" method="GET">
      {% csrf_token %}
      <button type="submit">{% if book_item.checkout %}Return{% endif %}{% if not book_item.checkout %}Checkout{% endif %}</button>
    </form>

    <a href="{% url 'libraryapp:delete_book' pk=book_item.pk %}" method="GET">
      <button type="submit">Delete</button>
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

library/templates/base_generic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>